# See https://github.com/hvr/multi-ghc-travis
# The following enables several GHC versions to be tested; often it's enough to test only against the last release in a major GHC version. Feel free to omit lines listings versions you don't need/want testing for.

notifications:
  email: false

sudo: false

env:
 - GHCVER=7.6.3  CABALVER=1.16
 - GHCVER=7.8.2  CABALVER=1.18
 - GHCVER=7.8.3  CABALVER=1.18
 - GHCVER=7.8.4  CABALVER=1.22
 - GHCVER=7.10.2 CABALVER=1.22
 - GHCVER=head   CABALVER=1.22

matrix:
  allow_failures:
   - env: GHCVER=head  CABALVER=1.22

cache:
  directories:
    - $HOME/.stack/

before_install:
 before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.5.0/stack-0.1.5.0-x86_64-linux.tar.gz | tar xz --strip-components=1 -C ~/.local/bin
  - chmod a+x ~/.local/bin/stack

install:
 - stack --no-terminal --skip-ghc-check install

script:
 - stack --no-terminal --skip-ghc-check build --test
 - stack --no-terminal --skip-ghc-check sdist